"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { LoaderCircle, MessagesSquare, Send } from "lucide-react";
import { waitingBadge } from "@/lib/waiting";
import { SUPPORT_TEMPLATES } from "@/lib/support-templates";
import "./support-ticket-board.css";

type Message = { id: string; body: string; sender_profile_id: string | null; sender_admin_id: string | null; created_at: string };
type Ticket = { id: string; subject: string; category: string; status: string; priority: string; last_message_at: string; profiles: { id: string; display_name: string } | null; support_ticket_messages: Message[] };

export function SupportTicketBoard() {
  const [openedAt] = useState(() => Date.now()); const [tickets, setTickets] = useState<Ticket[]>([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState(""); const [filter, setFilter] = useState("active");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/support", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) setTickets(body.tickets ?? []); else setNotice(body.error ?? "Destek kuyruğu yüklenemedi."); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => tickets.filter((ticket) => filter === "all" || (filter === "active" ? ticket.status !== "closed" : ticket.status === filter)), [filter, tickets]);
  const update = async (event: FormEvent<HTMLFormElement>, ticket: Ticket) => { event.preventDefault(); const form = new FormData(event.currentTarget); setNotice("İşlem kaydediliyor…"); const response = await fetch("/api/admin/support", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketId: ticket.id, status: form.get("status"), priority: form.get("priority"), reply: form.get("reply") }) }); const body = await response.json().catch(() => ({})); if (!response.ok) return setNotice(body.error ?? "İşlem kaydedilemedi."); setNotice("Destek talebi güncellendi."); await load(); };
  return <section className="ops-content support-board"><header><div><small>Üye yardım masası</small><h1>Canlı destek</h1></div><nav>{["active","open","waiting","in_progress","closed","all"].map((item) => <button className={filter === item ? "active" : ""} type="button" key={item} onClick={() => setFilter(item)}>{filterLabel(item)}{item !== "all" ? <b>{tickets.filter((ticket) => item === "active" ? ticket.status !== "closed" : ticket.status === item).length}</b> : null}</button>)}</nav></header>{notice ? <p className="ops-notice" role="status">{notice}</p> : null}{loading ? <div className="ops-empty"><LoaderCircle className="spin"/> Yükleniyor</div> : visible.length ? <div className="support-admin-list">{visible.map((ticket) => <article key={ticket.id}><header><span><small>{ticket.profiles?.display_name ?? "Kullanıcı"} · {categoryLabel(ticket.category)}</small><h2>{ticket.subject}</h2></span><i data-priority={ticket.priority}>{priorityLabel(ticket.priority)}</i>{ticket.status !== "closed" && waitingBadge(ticket.last_message_at, openedAt) ? <em className="wait-badge" data-tone={waitingBadge(ticket.last_message_at, openedAt)?.tone}>{waitingBadge(ticket.last_message_at, openedAt)?.label}</em> : null}</header><div className="support-admin-thread">{ticket.support_ticket_messages.toSorted((a,b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()).map((message) => <p className={message.sender_admin_id ? "admin" : "member"} key={message.id}><small>{message.sender_admin_id ? "Destek" : ticket.profiles?.display_name ?? "Kullanıcı"}</small>{message.body}</p>)}</div><form onSubmit={(event) => void update(event, ticket)}><label>Durum<select name="status" defaultValue={ticket.status}><option value="open">Açık</option><option value="waiting">Beklemede</option><option value="in_progress">İşleniyor</option><option value="closed">Kapalı</option></select></label><label>Öncelik<select name="priority" defaultValue={ticket.priority}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Yüksek</option><option value="urgent">Acil</option></select></label><label className="reply">Yanıt<select aria-label="Hazır yanıt" defaultValue="" onChange={(event) => { const field = event.currentTarget.form?.elements.namedItem("reply") as HTMLTextAreaElement | null; if (field && event.target.value) field.value = event.target.value; event.target.value = ""; }}><option value="">Hazır yanıt ekle…</option>{SUPPORT_TEMPLATES.map((template) => <option key={template.label} value={template.text}>{template.label}</option>)}</select><textarea name="reply" rows={2} maxLength={4000} placeholder="Kullanıcıya yanıt yaz…"/></label><button><Send size={15}/> Kaydet</button></form></article>)}</div> : <div className="ops-empty"><MessagesSquare/> Bu görünümde destek talebi yok.</div>}</section>;
}
function filterLabel(value: string) { return ({ active: "Aktif", open: "Açık", waiting: "Beklemede", in_progress: "İşleniyor", closed: "Kapalı", all: "Tümü" } as Record<string,string>)[value]; }
function categoryLabel(value: string) { return ({ account: "Hesap", payment: "Ödeme", safety: "Güvenlik", technical: "Teknik", other: "Diğer" } as Record<string,string>)[value] ?? value; }
function priorityLabel(value: string) { return ({ low: "Düşük", normal: "Normal", high: "Yüksek", urgent: "Acil" } as Record<string,string>)[value] ?? value; }
