"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, HardDrive, LoaderCircle, MemoryStick, RefreshCw, Server } from "lucide-react";
import "./system-health-panel.css";

type Health = { failedPaymentWebhooks: number; supabase: { databaseBytes: number; storageBytes: number; storageObjects: number; storageBuckets: number; legacyProfileRows: number; failedBotJobs: number; queuedBotJobs: number; openSupportTickets: number; pendingPhotos: number; largestTables: Array<{ name: string; bytes: number; rows: number }> }; limits: { database_limit_bytes: number; storage_limit_bytes: number }; server: { platform: string; node: string; uptimeSeconds: number; diskTotalBytes: number | null; diskUsedBytes: number | null; diskFreeBytes: number | null; heapUsedBytes: number; heapTotalBytes: number; rssBytes: number; systemMemoryBytes: number; freeSystemMemoryBytes: number }; measuredAt: string };

export function SystemHealthPanel() {
  const [health, setHealth] = useState<Health | null>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/health", { cache: "no-store" }); const body = await response.json().catch(() => ({})); if (response.ok) setHealth(body); else setNotice(body.error ?? "Sağlık ölçümü alınamadı."); setLoading(false); }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/health", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ databaseLimitBytes: Number(form.get("databaseGb")) * 1024 ** 3, storageLimitBytes: Number(form.get("storageGb")) * 1024 ** 3 }) }); const body = await response.json().catch(() => ({})); setNotice(response.ok ? "Paket sınırları güncellendi." : body.error ?? "Sınırlar kaydedilemedi."); if (response.ok) await load(); };
  if (loading && !health) return <section className="ops-content"><div className="ops-empty"><LoaderCircle className="spin"/> Sistem ölçülüyor</div></section>;
  if (!health) return <section className="ops-content"><p className="ops-notice">{notice}</p></section>;
  const db = ratio(health.supabase.databaseBytes, health.limits.database_limit_bytes); const storage = ratio(health.supabase.storageBytes, health.limits.storage_limit_bytes); const disk = health.server.diskTotalBytes ? ratio(health.server.diskUsedBytes ?? 0, health.server.diskTotalBytes) : null; const memory = ratio(health.server.rssBytes, health.server.systemMemoryBytes);
  const warnings = [db >= 80 ? `Veritabanı %${db} dolu.` : null, storage >= 80 ? `Storage %${storage} dolu.` : null, health.supabase.legacyProfileRows ? `${health.supabase.legacyProfileRows} eski WebP dışı fotoğraf kaydı var.` : null, health.supabase.failedBotJobs ? `${health.supabase.failedBotJobs} başarısız bot işi var.` : null, health.failedPaymentWebhooks ? `${health.failedPaymentWebhooks} başarısız ödeme bildirimi incelenmeli.` : null].filter(Boolean);
  return <section className="ops-content health-panel"><header><div><small>Kapasite ve erken uyarı</small><h1>Sistem sağlığı</h1><p>Supabase ve çalışan sunucu anlık olarak ölçülür.</p></div><button onClick={() => void load()}><RefreshCw size={15}/> Yenile</button></header>{notice ? <p className="ops-notice">{notice}</p> : null}<div className={warnings.length ? "health-summary warning" : "health-summary healthy"}>{warnings.length ? <AlertTriangle/> : <CheckCircle2/>}<span><strong>{warnings.length ? `${warnings.length} konu dikkat istiyor` : "Sistem rahat çalışıyor"}</strong><small>{warnings.join(" ") || "Kapasiteler güvenli aralıkta."}</small></span></div><div className="health-meters"><Meter icon={<Database/>} title="Supabase veritabanı" used={health.supabase.databaseBytes} total={health.limits.database_limit_bytes} percent={db} detail="Postgres tabloları ve indeksler"/><Meter icon={<HardDrive/>} title="Supabase Storage" used={health.supabase.storageBytes} total={health.limits.storage_limit_bytes} percent={storage} detail={`${health.supabase.storageObjects} nesne · ${health.supabase.storageBuckets} bucket`}/><Meter icon={<Server/>} title="Çalışma diski" used={health.server.diskUsedBytes} total={health.server.diskTotalBytes} percent={disk} detail={health.server.platform}/><Meter icon={<MemoryStick/>} title="Çalışma belleği" used={health.server.rssBytes} total={health.server.systemMemoryBytes} percent={memory} detail={`Heap ${formatBytes(health.server.heapUsedBytes)} · ${health.server.node}`}/></div><div className="health-detail-grid"><article><small>Operasyon yükü</small><dl><dt>Bekleyen fotoğraf</dt><dd>{health.supabase.pendingPhotos}</dd><dt>Açık destek</dt><dd>{health.supabase.openSupportTickets}</dd><dt>Kuyruktaki bot işi</dt><dd>{health.supabase.queuedBotJobs}</dd><dt>Başarısız bot işi</dt><dd>{health.supabase.failedBotJobs}</dd><dt>Başarısız ödeme bildirimi</dt><dd>{health.failedPaymentWebhooks}</dd><dt>WebP dışı eski kayıt</dt><dd>{health.supabase.legacyProfileRows}</dd></dl></article><article><small>En büyük tablolar</small><dl>{health.supabase.largestTables.map((table) => <span key={table.name}><dt>{table.name}<em>{Number(table.rows).toLocaleString("tr-TR")} satır</em></dt><dd>{formatBytes(table.bytes)}</dd></span>)}</dl></article><form onSubmit={save}><small>Paket sınırları</small><p>Yüzdelerin doğru olması için Supabase paketindeki limitleri yaz.</p><label>Veritabanı (GB)<input name="databaseGb" type="number" min="0.1" step="0.1" defaultValue={roundGb(health.limits.database_limit_bytes)}/></label><label>Storage (GB)<input name="storageGb" type="number" min="0.1" step="0.1" defaultValue={roundGb(health.limits.storage_limit_bytes)}/></label><button>Limitleri kaydet</button></form></div><footer>Son ölçüm: {new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "medium" }).format(new Date(health.measuredAt))}</footer></section>;
}
function Meter({ icon,title,used,total,percent,detail }: { icon: React.ReactNode; title: string; used: number | null; total: number | null; percent: number | null; detail: string }) { const level = percent === null ? "unknown" : percent >= 90 ? "danger" : percent >= 75 ? "warning" : "healthy"; return <article className={`health-meter ${level}`}><header><span>{icon}</span><i>{percent === null ? "—" : `%${percent}`}</i></header><h2>{title}</h2><p>{used === null || total === null ? "Bu ortamda ölçülemiyor" : `${formatBytes(used)} / ${formatBytes(total)}`}</p><div><i style={{ width: `${percent ?? 0}%` }}/></div><small>{detail}</small></article>; }
function ratio(used: number, total: number) { return Math.min(100, Math.round(used / total * 100)); }
function formatBytes(value: number) { if (!Number.isFinite(value)) return "—"; const units = ["B","KB","MB","GB","TB"]; let size = value; let unit = 0; while (size >= 1024 && unit < units.length - 1) { size /= 1024; unit++; } return `${size >= 10 || unit === 0 ? size.toFixed(0) : size.toFixed(1)} ${units[unit]}`; }
function roundGb(value: number) { return Math.round(value / 1024 ** 3 * 10) / 10; }

